site_name: SmartDNS
site_description: SmartDNS
site_author: pymumu
repo_name: 'pymumu/smartdns'
repo_url: 'https://github.com/pymumu/smartdns'

# Copyright
copyright: "Copyright &copy; Nick Peng"

theme:
  name: material
  logo: assets/smartdns.png
  feature:
    tabs: true
  favicon: 'assets/smartdns.png'
  language: 'zh'
  include_sidebar: false
  palette:
    - scheme: default
      primary: 'green'
      accent: 'green'
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: 'dark green'
      accent: 'dark green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.prune
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.code.copy

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  alternate:
    - name: 中文
      link: ./
      lang: zh
    - name: English
      link: en/ 
      lang: en

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - 首页: 'index.md'
  - 下载: 'download.md'
  - 安装: 
    - 标准Linux系统 / 树莓派: 'install/linux.md'
    - OpenWrt: 'install/openwrt.md'
    - 华硕固件 / 梅林固件: 'install/asus.md'
    - EntWare: 'install/entware.md'
    - WSL: 'install/wsl.md'
  - 配置示例:
    - 屏蔽广告: 'config/ad-block.md'
    - DNS分流: 'config/domain-forwarding.md'
    - 工作模式: 'config/work-mode.md'
    - Bootstrap DNS: 'config/bootstrap-dns.md'
    - 域名集合: 'config/domain-set.md'
    - IPSet和NFTSet: 'config/ipset-nftset.md'
    - 通过代理查询: 'config/proxy.md'
    - 解析本地主机名: 'config/resolv-dnsmasq-lease.md'
    - 缓存设置: 'config/cache.md'
    - 双栈优选: 'config/dualstack.md'
    - 禁用IPV6: 'config/block-ipv6.md'
    - DNS64: 'config/dns64.md'
    - 安全相关: 'config/security.md'
    - 黑名单分流请求: 'config/forwarding-with-ipset.md'
    - cname别名查询: 'config/cname.md'
  - 配置选项: 'configuration.md'
  - 编译: 'compile.md'
  - 常见问题: 'faq.md'
  - 捐赠: 'donate.md'